### ISSUE TITLE
[error] lessc.js:145 TypeError: undefined is not a function

### ISSUE THREAD

**Issue by sshark** [adrianhurt/play-silhouette-credentials-seed#3]
I ran into this error when I `sbt run` this project using `openjdk version "1.8.0_91"`. I have tried delete `project/target` and `project/project` as mentioned in [https://github.com/sbt/sbt-less/issues/80](https://github.com/sbt/sbt-less/issues/80) but it didn't help. Any pointer that could help me to investigate this issue? Thanks

```
[info] Compiling 4 Scala sources and 1 Java source to /workspace/play
ground/play-silhouette-credentials-seed/target/scala-2.11/classes...
[info] LESS compiling on 1 source(s)
[error] /workspace/playground/play-silhouette-credentials-seed/target
/less/lessc.js:145
[error]                 .then(handleResult, handleLessError);
[error]                  ^
[error] TypeError: undefined is not a function
[error]     at /workspace/playground/play-silhouette-credentials-seed
/target/less/lessc.js:145:18
[error]     at fs.js:334:14
[error]     at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by sshark** [comment]
I did a `npm -g install less` and it worked. Moving along, with a clean clone and had `less` removed via `npm -g uninstall less` it still worked. I never know what was the cause.
